version: '3.4'

services:

  front:
    build: .
    env_file: .env
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true

  server:
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - 3000:80